services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - internalNetwork
      - externalNetwork
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    container_name: mongodb
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
    networks:
      - internalNetwork
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-20-alpine3.18
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
    links:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - internalNetwork
      - externalNetwork
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodata:

networks:
  externalNetwork:
  internalNetwork:
